### ISSUE TITLE
Use of Union has Unexpected Results

### ISSUE THREAD

**Issue by tawheeler** [dpuyda/triclipper#1]
Hello! Thank you for the fantastic writeup on how the Vatti algorithm works.
I tried using the library, but am getting some weird results.

Here is an attempt at taking the union of two triangles:
```
clipper.AddTriangle({0, 0}, {0, 50}, {100, 0});
clipper.AddTriangle({0, 0}, {100, 50}, {100, 0});
clipper.Execute<OperationType::kUnion>();
```

This gives me:
```
2 polygon(s):

Polygon 0:
(0, 0)
(0, 50)
(50, 25)
(100, 0)

Polygon 1:
(100, 0)
(50, 25)
(100, 50)
```

when I expected the union to only be a single polygon.

Also, when I tried a more complicated example that was supposed to be the union of two boxes, I get two triangles that make up the bottom bit of the region:
```
clipper.AddTriangle({0, 0}, {100, 0}, {100, 100});
clipper.AddTriangle({0, 0}, {100, 100}, {0, 100});
clipper.AddTriangle({50, 50}, {150, 50}, {150, 150});
clipper.AddTriangle({50, 50}, {150, 150}, {50, 150});
clipper.Execute<OperationType::kUnion>();
```

2 polygon(s):

Polygon 0:
(0, 0)
(0, 50)
(50, 25)
(100, 0)

Polygon 1:
(100, 0)
(50, 25)
(100, 50)

**Comment by dpuyda** [comment]
Hello Tim!
Thank you very much for your interest in `triclipper`! I will take a look into this issue and will fix it as soon as possible.

Best regards
Dmytro.

**Comment by dpuyda** [comment]
Hello Tim!

Thanks again for your interest in my pet project. I have updated `triclipper` to address your comments. Please see the notes below for details.

Please let me know if you have any further questions and if I can close this issue. If you have any other issues with using `triclipper`, I would be very grateful if you could let me know. Also, if you need to update `triclipper` to suit your needs, please let me know as well and I will try to help you.

1. Let us consider your first example:
    ```cpp
    clipper.AddTriangle({0, 0}, {0, 50}, {100, 0});
    clipper.AddTriangle({0, 0}, {100, 50}, {100, 0});
    clipper.Execute<OperationType::kUnion>();
    ```
    In this test case, `triclipper` prints the following output:
    ```
    2 polygon(s):
    
    Polygon 0:
    (0, 0)
    (0, 50)
    (50, 25)
    (100, 0)
    
    Polygon 1:
    (100, 0)
    (50, 25)
    (100, 50)
    ```
    
    This output looks correct to me. Please note that `triclipper` represents the result as a collection of disjoint **monotone polygons**. Let us consider this example in more detail.
    
    In this example, you add two triangles (0, 0)-(0, 50)-(100, 0) and (0, 0)-(100, 50)-(100, 0) that look as follows:
    
    ![1-1](https://user-images.githubusercontent.com/36919390/213860445-f5d19089-e692-45c7-be67-08d9fcaddcfc.svg)
    
    ![1-2](https://user-images.githubusercontent.com/36919390/213860449-7b10cd09-da13-408e-99fc-e280dbd20809.svg)
    
    The union of these triangles is one **non-monotone polygon** that looks like this:
    
    ![1-3](https://user-images.githubusercontent.com/36919390/213860476-187a6a70-e3a7-4b2d-993a-50028efac7ab.svg)
    
    Since this polygon is non-monotone, `triclipper` represents it as a union of **two monotone polygons** (0, 0)-(0, 50)-(50, 25)-(100, 0) and (100, 0)-(50, 25)-(100, 50) that look like this:
    
    ![1-4](https://user-images.githubusercontent.com/36919390/213860549-e0d52898-e923-4a1e-8e85-5e5c8450146e.svg)

    This looks correct to me. To avoid confusion, I have renamed `GetPolygons` to `GetMonotonePolygons`.

    **Why monotone polygons?**

    `triclipper` represents the result in form of monotone polygons because monotone polygons are more suitable for rendering than non-monotone polygons.

    To render a polygon, we usually have to split it into triangles or triangle strips. Representing a **monotone polygon** as a triangle strip is a simple operation, while representing a **non-monotone polygon** as a collection of triangle strips is usually more complex and often involves splitting the polygon into monotone polygons. When using the sweep-line algorithm, we naturally obtain the result in form of a collection of monotone polygons first, so there is usually no need to join them into a non-monotone polygon that will have to be split (potentially back into monotone polygons) later.

    **Where can this be used?**

    As you can guess, `kUnion` can be used to render a collection of overlapping polygons without overdraw. Reducing overdraw sometimes can improve rendering performance significantly.

3. In your second example, you add for triangles as below:

    ```cpp
    clipper.AddTriangle({0, 0}, {100, 0}, {100, 100});
    clipper.AddTriangle({0, 0}, {100, 100}, {0, 100});
    clipper.AddTriangle({50, 50}, {150, 50}, {150, 150});
    clipper.AddTriangle({50, 50}, {150, 150}, {50, 150});
    ```
    
    The union of these triangles is one **monotone polygon** which looks like this:
    
    ![2-1](https://user-images.githubusercontent.com/36919390/213861485-4b517aa9-aee2-4907-82e5-3318d90389a5.svg)
    
    After the fix, `triclipper` produces the following output:
    
    ```
    1 polygon(s):
    
    Polygon 0:
    (0, 0)
    (0, 100)
    (50, 100)
    (50, 150)
    (150, 150)
    (150, 50)
    (100, 50)
    (100, 0)
    ```
    
    The issue consisted in the fact that before the fix, `triclipper` was trying to join polygons even when there was no polygon on the right. I have added this test case to unit tests. I will test this more carefully and add more test cases a little later when I have time. Thanks a lot for finding this issue!

**Comment by tawheeler** [comment]
Thank you for the very clear explanation and the very quick fix!
